using Microsoft.AspNetCore.Identity;

namespace CptcEvents.Models;

public static class DevSeedEvents
{
    public static List<Event> Create(Group systemEventsGroup, IdentityUser adminUser)
    {
        if (systemEventsGroup == null) throw new ArgumentNullException(nameof(systemEventsGroup));
        if (adminUser == null) throw new ArgumentNullException(nameof(adminUser));

        return new List<Event>
        {
            // Summer 2025 Quarter Events
            new Event { Title = "Summer 2025 - Priority Registration", Description = "Priority registration for Summer 2025 quarter", DateOfEvent = new DateOnly(2025, 5, 19), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Summer 2025 - Continuing Student Registration", Description = "Registration period for continuing students (May 20-23)", DateOfEvent = new DateOnly(2025, 5, 20), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Summer 2025 - Open Registration", Description = "Open registration for all admitted students (May 27 - July 2)", DateOfEvent = new DateOnly(2025, 5, 27), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Summer 2025 - Tuition & Fees Deadline", Description = "Deadline for tuition and fees payment", DateOfEvent = new DateOnly(2025, 6, 17), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Summer 2025 - First Day of Quarter", Description = "First day of Summer 2025 quarter", DateOfEvent = new DateOnly(2025, 7, 1), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Summer 2025 - Last Day to Drop (100% Refund)", Description = "Last day to drop with 100% refund", DateOfEvent = new DateOnly(2025, 7, 8), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Summer 2025 - Last Day to Withdraw (50% Refund)", Description = "Last day to withdraw with 50% refund", DateOfEvent = new DateOnly(2025, 7, 29), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Summer 2025 - Last Day to Withdraw (W Grade)", Description = "Last day to withdraw with W grade", DateOfEvent = new DateOnly(2025, 8, 19), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Summer 2025 - Graduation Application Deadline", Description = "Deadline for graduation application", DateOfEvent = new DateOnly(2025, 7, 25), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Summer 2025 - Last Day of Quarter", Description = "Last day of Summer 2025 quarter", DateOfEvent = new DateOnly(2025, 9, 2), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Summer 2025 - Official Grades Posted", Description = "Official grades on transcript (ccLink)", DateOfEvent = new DateOnly(2025, 9, 8), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },

            // Fall 2025 Quarter Events
            new Event { Title = "Fall 2025 - Priority Registration", Description = "Priority registration for Fall 2025 quarter", DateOfEvent = new DateOnly(2025, 5, 19), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Fall 2025 - Continuing Student Registration", Description = "Registration period for continuing students (May 20-23)", DateOfEvent = new DateOnly(2025, 5, 20), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Fall 2025 - Open Registration", Description = "Open registration for all admitted students (May 27 - Sept 30)", DateOfEvent = new DateOnly(2025, 5, 27), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Fall 2025 - Tuition & Fees Deadline", Description = "Deadline for tuition and fees payment", DateOfEvent = new DateOnly(2025, 9, 15), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Fall 2025 - First Day of Quarter", Description = "First day of Fall 2025 quarter", DateOfEvent = new DateOnly(2025, 9, 29), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Fall 2025 - Last Day to Drop (100% Refund)", Description = "Last day to drop with 100% refund", DateOfEvent = new DateOnly(2025, 10, 3), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Fall 2025 - Last Day to Withdraw (50% Refund)", Description = "Last day to withdraw with 50% refund", DateOfEvent = new DateOnly(2025, 10, 28), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Fall 2025 - Last Day to Withdraw (W Grade)", Description = "Last day to withdraw with W grade", DateOfEvent = new DateOnly(2025, 11, 19), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Fall 2025 - Graduation Application Deadline", Description = "Deadline for graduation application", DateOfEvent = new DateOnly(2025, 10, 24), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Fall 2025 - Last Day of Quarter", Description = "Last day of Fall 2025 quarter", DateOfEvent = new DateOnly(2025, 12, 12), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Fall 2025 - Official Grades Posted", Description = "Official grades on transcript (ccLink)", DateOfEvent = new DateOnly(2025, 12, 18), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },

            // Winter 2026 Quarter Events
            new Event { Title = "Winter 2026 - Priority Registration", Description = "Priority registration for Winter 2026 quarter", DateOfEvent = new DateOnly(2025, 11, 17), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Winter 2026 - Continuing Student Registration", Description = "Registration period for continuing students (Nov 18-21)", DateOfEvent = new DateOnly(2025, 11, 18), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Winter 2026 - Open Registration", Description = "Open registration for all admitted students (Nov 24 - Jan 6)", DateOfEvent = new DateOnly(2025, 11, 24), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Winter 2026 - Tuition & Fees Deadline", Description = "Deadline for tuition and fees payment", DateOfEvent = new DateOnly(2025, 12, 18), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Winter 2026 - First Day of Quarter", Description = "First day of Winter 2026 quarter", DateOfEvent = new DateOnly(2026, 1, 5), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Winter 2026 - Last Day to Drop (100% Refund)", Description = "Last day to drop with 100% refund", DateOfEvent = new DateOnly(2026, 1, 9), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Winter 2026 - Last Day to Withdraw (50% Refund)", Description = "Last day to withdraw with 50% refund", DateOfEvent = new DateOnly(2026, 2, 2), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Winter 2026 - Last Day to Withdraw (W Grade)", Description = "Last day to withdraw with W grade", DateOfEvent = new DateOnly(2026, 2, 24), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Winter 2026 - Graduation Application Deadline", Description = "Deadline for graduation application", DateOfEvent = new DateOnly(2026, 1, 30), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Winter 2026 - Last Day of Quarter", Description = "Last day of Winter 2026 quarter", DateOfEvent = new DateOnly(2026, 3, 18), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Winter 2026 - Official Grades Posted", Description = "Official grades on transcript (ccLink)", DateOfEvent = new DateOnly(2026, 3, 24), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },

            // Spring 2026 Quarter Events
            new Event { Title = "Spring 2026 - Priority Registration", Description = "Priority registration for Spring 2026 quarter", DateOfEvent = new DateOnly(2026, 2, 2), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Spring 2026 - Continuing Student Registration", Description = "Registration period for continuing students (Feb 3-6)", DateOfEvent = new DateOnly(2026, 2, 3), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Spring 2026 - Open Registration", Description = "Open registration for all admitted students (Feb 9 - Mar 31)", DateOfEvent = new DateOnly(2026, 2, 9), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Spring 2026 - Tuition & Fees Deadline", Description = "Deadline for tuition and fees payment", DateOfEvent = new DateOnly(2026, 3, 16), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Spring 2026 - First Day of Quarter", Description = "First day of Spring 2026 quarter", DateOfEvent = new DateOnly(2026, 3, 30), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Spring 2026 - Last Day to Drop (100% Refund)", Description = "Last day to drop with 100% refund", DateOfEvent = new DateOnly(2026, 4, 3), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Spring 2026 - Last Day to Withdraw (50% Refund)", Description = "Last day to withdraw with 50% refund", DateOfEvent = new DateOnly(2026, 4, 24), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Spring 2026 - Last Day to Withdraw (W Grade)", Description = "Last day to withdraw with W grade", DateOfEvent = new DateOnly(2026, 5, 18), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Spring 2026 - Graduation Application Deadline", Description = "Deadline for graduation application", DateOfEvent = new DateOnly(2026, 4, 24), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Spring 2026 - Last Day of Quarter", Description = "Last day of Spring 2026 quarter", DateOfEvent = new DateOnly(2026, 6, 9), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Spring 2026 - Official Grades Posted", Description = "Official grades on transcript (ccLink)", DateOfEvent = new DateOnly(2026, 6, 15), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },

            // Financial Aid Deadlines
            new Event { Title = "Summer 2025 - Financial Aid Application Deadline", Description = "Deadline for CPTC Financial Aid application process", DateOfEvent = new DateOnly(2025, 5, 23), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Fall 2025 - Financial Aid Application Deadline", Description = "Deadline for CPTC Financial Aid application process", DateOfEvent = new DateOnly(2025, 6, 27), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Winter 2026 - Financial Aid Application Deadline", Description = "Deadline for CPTC Financial Aid application process", DateOfEvent = new DateOnly(2025, 11, 14), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id },
            new Event { Title = "Spring 2026 - Financial Aid Application Deadline", Description = "Deadline for CPTC Financial Aid application process", DateOfEvent = new DateOnly(2026, 2, 20), IsAllDay = true, IsPublic = true, IsApprovedPublic = true, GroupId = systemEventsGroup.Id, CreatedByUserId = adminUser.Id }
        };
    }
}