services:
  sqlserver-dev:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-dev
    hostname: sqlserver-dev
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA_PASSWORD}
      - CPTCEVENTS_DB_PASSWORD=${CPTCEVENTS_DB_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - data:/var/opt/mssql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    restart: unless-stopped
    networks:
      - CptcEventsNetwork

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite-dev
    hostname: azurite-dev
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite-data:/data
    command: azurite --skipApiVersionCheck --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0
    restart: unless-stopped
    networks:
      - CptcEventsNetwork

volumes:
  data:
  azurite-data:

networks:
  CptcEventsNetwork:
    external: true