// <auto-generated />
using System;
using CptcEvents.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CptcEvents.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260126203706_AddEvenRSVP")]
    partial class AddEvenRSVP
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CptcEvents.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-user-id",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "18b10a7e-f077-4ae7-9cbd-0f2ba31ca4dd",
                            Email = "admin@cptc.edu",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@CPTC.EDU",
                            NormalizedUserName = "ADMIN@CPTC.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAEKUohHSj6nzqDqpT3TkPPzfJaP9LuIQt553VdEvlQXwMoj9TV8+gsE3WtXVRxl1otg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ccecebf8-9ebe-47fb-860d-6f9c2f10e926",
                            TwoFactorEnabled = false,
                            UserName = "admin@cptc.edu"
                        });
                });

            modelBuilder.Entity("CptcEvents.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("DateOfEvent")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApprovedPublic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeniedPublic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("GroupId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2025, 5, 19),
                            Description = "Priority registration for Summer 2025 quarter",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Summer 2025 - Priority Registration"
                        },
                        new
                        {
                            Id = 2,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2025, 5, 20),
                            Description = "Registration period for continuing students (May 20-23)",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Summer 2025 - Continuing Student Registration"
                        },
                        new
                        {
                            Id = 3,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2025, 5, 27),
                            Description = "Open registration for all admitted students (May 27 - July 2)",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Summer 2025 - Open Registration"
                        },
                        new
                        {
                            Id = 4,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2025, 6, 17),
                            Description = "Deadline for tuition and fees payment",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Summer 2025 - Tuition & Fees Deadline"
                        },
                        new
                        {
                            Id = 5,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2025, 7, 1),
                            Description = "First day of Summer 2025 quarter",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Summer 2025 - First Day of Quarter"
                        },
                        new
                        {
                            Id = 6,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2025, 7, 8),
                            Description = "Last day to drop with 100% refund",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Summer 2025 - Last Day to Drop (100% Refund)"
                        },
                        new
                        {
                            Id = 7,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2025, 7, 29),
                            Description = "Last day to withdraw with 50% refund",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Summer 2025 - Last Day to Withdraw (50% Refund)"
                        },
                        new
                        {
                            Id = 8,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2025, 8, 19),
                            Description = "Last day to withdraw with W grade",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Summer 2025 - Last Day to Withdraw (W Grade)"
                        },
                        new
                        {
                            Id = 9,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2025, 7, 25),
                            Description = "Deadline for graduation application",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Summer 2025 - Graduation Application Deadline"
                        },
                        new
                        {
                            Id = 10,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2025, 9, 2),
                            Description = "Last day of Summer 2025 quarter",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Summer 2025 - Last Day of Quarter"
                        },
                        new
                        {
                            Id = 11,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2025, 9, 8),
                            Description = "Official grades on transcript (ccLink)",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Summer 2025 - Official Grades Posted"
                        },
                        new
                        {
                            Id = 12,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2025, 5, 19),
                            Description = "Priority registration for Fall 2025 quarter",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Fall 2025 - Priority Registration"
                        },
                        new
                        {
                            Id = 13,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2025, 5, 20),
                            Description = "Registration period for continuing students (May 20-23)",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Fall 2025 - Continuing Student Registration"
                        },
                        new
                        {
                            Id = 14,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2025, 5, 27),
                            Description = "Open registration for all admitted students (May 27 - Sept 30)",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Fall 2025 - Open Registration"
                        },
                        new
                        {
                            Id = 15,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2025, 9, 15),
                            Description = "Deadline for tuition and fees payment",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Fall 2025 - Tuition & Fees Deadline"
                        },
                        new
                        {
                            Id = 16,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2025, 9, 29),
                            Description = "First day of Fall 2025 quarter",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Fall 2025 - First Day of Quarter"
                        },
                        new
                        {
                            Id = 17,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2025, 10, 3),
                            Description = "Last day to drop with 100% refund",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Fall 2025 - Last Day to Drop (100% Refund)"
                        },
                        new
                        {
                            Id = 18,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2025, 10, 28),
                            Description = "Last day to withdraw with 50% refund",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Fall 2025 - Last Day to Withdraw (50% Refund)"
                        },
                        new
                        {
                            Id = 19,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2025, 11, 19),
                            Description = "Last day to withdraw with W grade",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Fall 2025 - Last Day to Withdraw (W Grade)"
                        },
                        new
                        {
                            Id = 20,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2025, 10, 24),
                            Description = "Deadline for graduation application",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Fall 2025 - Graduation Application Deadline"
                        },
                        new
                        {
                            Id = 21,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2025, 12, 12),
                            Description = "Last day of Fall 2025 quarter",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Fall 2025 - Last Day of Quarter"
                        },
                        new
                        {
                            Id = 22,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2025, 12, 18),
                            Description = "Official grades on transcript (ccLink)",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Fall 2025 - Official Grades Posted"
                        },
                        new
                        {
                            Id = 23,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2025, 11, 17),
                            Description = "Priority registration for Winter 2026 quarter",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Winter 2026 - Priority Registration"
                        },
                        new
                        {
                            Id = 24,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2025, 11, 18),
                            Description = "Registration period for continuing students (Nov 18-21)",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Winter 2026 - Continuing Student Registration"
                        },
                        new
                        {
                            Id = 25,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2025, 11, 24),
                            Description = "Open registration for all admitted students (Nov 24 - Jan 6)",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Winter 2026 - Open Registration"
                        },
                        new
                        {
                            Id = 26,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2025, 12, 18),
                            Description = "Deadline for tuition and fees payment",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Winter 2026 - Tuition & Fees Deadline"
                        },
                        new
                        {
                            Id = 27,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2026, 1, 5),
                            Description = "First day of Winter 2026 quarter",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Winter 2026 - First Day of Quarter"
                        },
                        new
                        {
                            Id = 28,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2026, 1, 9),
                            Description = "Last day to drop with 100% refund",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Winter 2026 - Last Day to Drop (100% Refund)"
                        },
                        new
                        {
                            Id = 29,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2026, 2, 2),
                            Description = "Last day to withdraw with 50% refund",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Winter 2026 - Last Day to Withdraw (50% Refund)"
                        },
                        new
                        {
                            Id = 30,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2026, 2, 24),
                            Description = "Last day to withdraw with W grade",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Winter 2026 - Last Day to Withdraw (W Grade)"
                        },
                        new
                        {
                            Id = 31,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2026, 1, 30),
                            Description = "Deadline for graduation application",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Winter 2026 - Graduation Application Deadline"
                        },
                        new
                        {
                            Id = 32,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2026, 3, 18),
                            Description = "Last day of Winter 2026 quarter",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Winter 2026 - Last Day of Quarter"
                        },
                        new
                        {
                            Id = 33,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2026, 3, 24),
                            Description = "Official grades on transcript (ccLink)",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Winter 2026 - Official Grades Posted"
                        },
                        new
                        {
                            Id = 34,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2026, 2, 2),
                            Description = "Priority registration for Spring 2026 quarter",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Spring 2026 - Priority Registration"
                        },
                        new
                        {
                            Id = 35,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2026, 2, 3),
                            Description = "Registration period for continuing students (Feb 3-6)",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Spring 2026 - Continuing Student Registration"
                        },
                        new
                        {
                            Id = 36,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2026, 2, 9),
                            Description = "Open registration for all admitted students (Feb 9 - Mar 31)",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Spring 2026 - Open Registration"
                        },
                        new
                        {
                            Id = 37,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2026, 3, 16),
                            Description = "Deadline for tuition and fees payment",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Spring 2026 - Tuition & Fees Deadline"
                        },
                        new
                        {
                            Id = 38,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2026, 3, 30),
                            Description = "First day of Spring 2026 quarter",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Spring 2026 - First Day of Quarter"
                        },
                        new
                        {
                            Id = 39,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2026, 4, 3),
                            Description = "Last day to drop with 100% refund",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Spring 2026 - Last Day to Drop (100% Refund)"
                        },
                        new
                        {
                            Id = 40,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2026, 4, 24),
                            Description = "Last day to withdraw with 50% refund",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Spring 2026 - Last Day to Withdraw (50% Refund)"
                        },
                        new
                        {
                            Id = 41,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2026, 5, 18),
                            Description = "Last day to withdraw with W grade",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Spring 2026 - Last Day to Withdraw (W Grade)"
                        },
                        new
                        {
                            Id = 42,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2026, 4, 24),
                            Description = "Deadline for graduation application",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Spring 2026 - Graduation Application Deadline"
                        },
                        new
                        {
                            Id = 43,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2026, 6, 9),
                            Description = "Last day of Spring 2026 quarter",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Spring 2026 - Last Day of Quarter"
                        },
                        new
                        {
                            Id = 44,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2026, 6, 15),
                            Description = "Official grades on transcript (ccLink)",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Spring 2026 - Official Grades Posted"
                        },
                        new
                        {
                            Id = 45,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2025, 5, 23),
                            Description = "Deadline for CPTC Financial Aid application process",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Summer 2025 - Financial Aid Application Deadline"
                        },
                        new
                        {
                            Id = 46,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2025, 6, 27),
                            Description = "Deadline for CPTC Financial Aid application process",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Fall 2025 - Financial Aid Application Deadline"
                        },
                        new
                        {
                            Id = 47,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2025, 11, 14),
                            Description = "Deadline for CPTC Financial Aid application process",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Winter 2026 - Financial Aid Application Deadline"
                        },
                        new
                        {
                            Id = 48,
                            CreatedByUserId = "admin-user-id",
                            DateOfEvent = new DateOnly(2026, 2, 20),
                            Description = "Deadline for CPTC Financial Aid application process",
                            EndTime = new TimeOnly(0, 0, 0),
                            GroupId = 1,
                            IsAllDay = true,
                            IsApprovedPublic = true,
                            IsDeniedPublic = false,
                            IsPublic = true,
                            StartTime = new TimeOnly(0, 0, 0),
                            Title = "Spring 2026 - Financial Aid Application Deadline"
                        });
                });

            modelBuilder.Entity("CptcEvents.Models.EventRsvp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("EventId", "UserId")
                        .IsUnique();

                    b.ToTable("EventRsvps");
                });

            modelBuilder.Entity("CptcEvents.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PrivacyLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#502a7f",
                            CreatedAt = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default group for CPTC events and announcements",
                            Name = "Cptc Dates",
                            OwnerId = "admin-user-id",
                            PrivacyLevel = 0
                        });
                });

            modelBuilder.Entity("CptcEvents.Models.GroupInvite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InvitedUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("OneTimeUse")
                        .HasColumnType("bit");

                    b.Property<int>("TimesUsed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("GroupId");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.HasIndex("InvitedUserId");

                    b.ToTable("GroupInvites");
                });

            modelBuilder.Entity("CptcEvents.Models.GroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int?>("InviteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("GroupId");

                    b.HasIndex("InviteId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupMemberships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupId = 1,
                            JoinedAt = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = 2,
                            UserId = "admin-user-id"
                        });
                });

            modelBuilder.Entity("CptcEvents.Models.InstructorCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InstructorCodes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-role-id",
                            ConcurrencyStamp = "6c4dd18c-9346-454b-be3b-eb079e89b0a6",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "staff-role-id",
                            ConcurrencyStamp = "ad46fdc8-be6e-4a26-b637-0dd6578e7984",
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        },
                        new
                        {
                            Id = "student-role-id",
                            ConcurrencyStamp = "20274bea-9795-4c65-a591-7f99a9784856",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "admin-user-id",
                            RoleId = "admin-role-id"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CptcEvents.Models.Event", b =>
                {
                    b.HasOne("CptcEvents.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CptcEvents.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CptcEvents.Models.EventRsvp", b =>
                {
                    b.HasOne("CptcEvents.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CptcEvents.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CptcEvents.Models.Group", b =>
                {
                    b.HasOne("CptcEvents.Models.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CptcEvents.Models.GroupInvite", b =>
                {
                    b.HasOne("CptcEvents.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CptcEvents.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CptcEvents.Models.ApplicationUser", "InvitedUser")
                        .WithMany()
                        .HasForeignKey("InvitedUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("Group");

                    b.Navigation("InvitedUser");
                });

            modelBuilder.Entity("CptcEvents.Models.GroupMember", b =>
                {
                    b.HasOne("CptcEvents.Models.ApplicationUser", null)
                        .WithMany("GroupMemberships")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("CptcEvents.Models.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CptcEvents.Models.GroupInvite", "Invite")
                        .WithMany("CreatedMemberships")
                        .HasForeignKey("InviteId");

                    b.HasOne("CptcEvents.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Invite");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CptcEvents.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CptcEvents.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CptcEvents.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CptcEvents.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CptcEvents.Models.ApplicationUser", b =>
                {
                    b.Navigation("GroupMemberships");
                });

            modelBuilder.Entity("CptcEvents.Models.Group", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("CptcEvents.Models.GroupInvite", b =>
                {
                    b.Navigation("CreatedMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
